CREATE TABLE IF NOT EXISTS users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             VARCHAR(255) NOT NULL UNIQUE,
    password             VARCHAR(255),
    full_name            VARCHAR(255),
    role                 VARCHAR(50)  NOT NULL,
    auth_provider        VARCHAR(50),
    verified             BOOLEAN      NOT NULL DEFAULT FALSE,
    must_change_password BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS otp_verification (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL,
    otp      VARCHAR(10)  NOT NULL,
    verified BOOLEAN      NOT NULL DEFAULT FALSE,
    expiry   TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS client_profile (
    id            UUID         DEFAULT RANDOM_UUID() PRIMARY KEY,
    first_name    VARCHAR(100),
    last_name     VARCHAR(100),
    email_address VARCHAR(255),
    phone         VARCHAR(50),
    address       VARCHAR(255),
    company_name  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS auditor_profile (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name           VARCHAR(100),
    last_name            VARCHAR(100),
    email_address        VARCHAR(255),
    phone                VARCHAR(50),
    certification_number VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS organisation (
    id                UUID         DEFAULT RANDOM_UUID() PRIMARY KEY,
    client_id         UUID         NOT NULL,
    name              VARCHAR(255) NOT NULL,
    industry          VARCHAR(100),
    fiscal_year_start VARCHAR(5)   NOT NULL DEFAULT '01-01',
    fiscal_year_end   VARCHAR(5)   NOT NULL DEFAULT '12-31',
    default_currency  VARCHAR(10)  NOT NULL DEFAULT 'USD',
    created_at        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS organisation_member (
    id              UUID        DEFAULT RANDOM_UUID() PRIMARY KEY,
    organisation_id UUID        NOT NULL,
    user_id         BIGINT      NOT NULL,
    role            VARCHAR(20) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    joined_at       TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_org_member UNIQUE (organisation_id, user_id)
);

CREATE TABLE IF NOT EXISTS organisation_currency (
    id              UUID        DEFAULT RANDOM_UUID() PRIMARY KEY,
    organisation_id UUID        NOT NULL,
    currency_code   VARCHAR(10) NOT NULL,
    is_default      BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_org_currency UNIQUE (organisation_id, currency_code)
);

CREATE TABLE IF NOT EXISTS organisation_invitation (
    id              UUID         DEFAULT RANDOM_UUID() PRIMARY KEY,
    organisation_id UUID         NOT NULL,
    invited_email   VARCHAR(255) NOT NULL,
    role            VARCHAR(20)  NOT NULL,
    token           VARCHAR(255) NOT NULL UNIQUE,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    invited_by      UUID         NOT NULL,
    expires_at      TIMESTAMP    NOT NULL,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);